### ISSUE TITLE
taxonlookup not on CRAN, current version of MS says that it will be

### ISSUE THREAD

**Issue by wcornwell** [mwpennell/phyndr-ms#27]
when we discussed this before, it was blocked by storr which was blocked by something else, which had an important bug or something like that?  any progress on that?

**Comment by richfitz** [comment]
phyndr is not blocked by anything - only taxonlookup is.  And storr is still blocked by RedisAPI because I'm rewriting the Redis support and don't want two versions of that up...

**Comment by wcornwell** [comment]
I'm OK with `taxonlookup` not being on CRAN, I'll take that out of the MS...

**Comment by wcornwell** [comment]
see 72a7375e0ae49637d0ff5b932a407dca6a4bc494
